# Generated by Django 5.0.1 on 2025-11-02 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Room display name', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly room ideantifier', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Room description', max_length=500)),
                ('room_type', models.CharField(choices=[('private', 'Private Chat'), ('group', 'Group Chat'), ('public', 'Public Room')], default='private', max_length=10)),
                ('max_members', models.PositiveIntegerField(default=50, help_text='Maximum number of members allowed')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this room', on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'db_table': 'chat_rooms',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Message content')),
                ('emotion', models.CharField(blank=True, choices=[('happy', '😊 Happy'), ('sad', '😢 Sad'), ('angry', '😠 Angry'), ('surprised', '😲 Surprised'), ('fearful', '😨 Fearful'), ('disgusted', ' Disgusted'), ('neutral', '😐 Neutral'), ('positive', ' Positive'), ('negative', '😞 Negative')], help_text='Detected emotion', max_length=20)),
                ('emotion_confidence', models.FloatField(default=0.0, help_text='Confidence score (0.0 to 1.0)')),
                ('sentiment_polarity', models.FloatField(default=0.0, help_text='Sentiment polarity (-1.0 to 1.0)')),
                ('sentiment_subjectivity', models.FloatField(default=0.0, help_text='Sentiment subjectivity (0.0 to 1.0)')),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('image', 'Image'), ('file', 'File'), ('system', 'System Message')], default='text', max_length=20)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('sender', models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(help_text='Room where message was sent', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.room')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chat_messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RoomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=10)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Room Membership',
                'verbose_name_plural': 'Room Memberships',
                'db_table': 'chat_room_memberships',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(help_text='Users in this room', related_name='chat_rooms', through='chat.RoomMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmotionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_score', models.FloatField(default=0.0)),
                ('sad_score', models.FloatField(default=0.0)),
                ('angry_score', models.FloatField(default=0.0)),
                ('surprised_score', models.FloatField(default=0.0)),
                ('fearful_score', models.FloatField(default=0.0)),
                ('disgusted_score', models.FloatField(default=0.0)),
                ('room_type', models.CharField(max_length=20)),
                ('message_length', models.PositiveIntegerField()),
                ('time_of_day', models.TimeField()),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_logs', to=settings.AUTH_USER_MODEL)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_log', to='chat.message')),
            ],
            options={
                'verbose_name': 'Emotion Log',
                'verbose_name_plural': 'Emotion Logs',
                'db_table': 'emotion_logs',
                'indexes': [models.Index(fields=['user', 'analyzed_at'], name='emotion_log_user_id_eaa7eb_idx'), models.Index(fields=['room_type'], name='emotion_log_room_ty_c3c163_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'timestamp'], name='chat_messag_room_id_b9c732_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'timestamp'], name='chat_messag_sender__e614c8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['emotion'], name='chat_messag_emotion_919b87_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roommembership',
            unique_together={('room', 'user')},
        ),
    ]
