# Generated by Django 5.0.1 on 2025-11-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', help_text='Upload a profile picture', null=True, upload_to='profile_pics/'),
        ),
    ]
